---
abstract: 'Minify your served JavaScript files'
author:
  - 'Ivan Drinchev <drinchev (at) gmail (dot) com>'
  - "Arthur Axel \"fREW\" Schmidt <frioux@gmail.com>"
generated_by: 'Dist::Zilla version 1.093400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-JavaScript-Minifier-XS
requires:
  Catalyst: 5.8000
  Catalyst::Test: 0
  File::Spec: 0
  FindBin: 0
  HTTP::Headers: 0
  HTTP::Request: 0
  JavaScript::Minifier::XS: 0
  Moose: 0
  Path::Class::File: 0.17
  Test::More: 0.88
  URI: 0
  autodie: 0
  parent: 0
resources:
  repository: http://github.com/frioux/Catalyst-View-JavaScript-Minifier-XS
version: 1.093530
