---
abstract: 'Minify your served JavaScript files'
author:
  - 'Ivan Drinchev <drinchev (at) gmail (dot) com>'
  - 'Arthur Axel "fREW" Schmidt <frioux@gmail.com>'
build_requires:
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catalyst-View-JavaScript-Minifier-XS
requires:
  Catalyst: '5.64'
  Catalyst::Test: '0'
  File::Spec: '0'
  FindBin: '0'
  HTTP::Headers: '0'
  HTTP::Request: '0'
  JavaScript::Minifier::XS: '0'
  Moose: '0'
  MooseX::Aliases: '0'
  Path::Class::Dir: '0.17'
  URI: '0'
  autodie: '0'
  parent: '0'
resources:
  bugtracker: https://github.com/frioux/Catalyst-View-JavaScript-Minifier-XS/issues
  homepage: https://github.com/frioux/Catalyst-View-JavaScript-Minifier-XS
  repository: https://github.com/frioux/Catalyst-View-JavaScript-Minifier-XS.git
version: '2.102000'
