--- #YAML:1.0
name:                Catalyst-View-JavaScript-Minifier-XS
version:             0.04
abstract:            Concenate and minify your JavaScript files.
license:             perl
author:              
    - Ivan Drinchev <drinchev@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Catalyst:                      5.64
    ExtUtils::MakeMaker:           6.3002
    JavaScript::Minifier::XS:      0
    parent:                        0
    Path::Class:                   0.17
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
